sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t sagarawale/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sagarawale/docker-react npm run test
